name: test_task_kz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^8.1.3
  freezed: ^2.2.1
  formz: ^0.4.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  keyboard_dismisser: ^3.0.0
  flutter_svg: ^2.0.7
  cached_network_image:
  shimmer:
  shared_preferences: ^2.2.0
  dio_logging_interceptor: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.1.4

flutter:


  uses-material-design: true

  assets:
     - assets/
